apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-test-secret-03202-development
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/go-test-secret-03202/overlays/development
    repoURL: https://github.com/stephanie-cy/go-test-secret-03202-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-development
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - kind: Repository
    jsonPointers:
      - /spec
      - /spec/params
      - /spec/secret
      - /spec/webhook_secret
    jqPathExpressions:
      - .spec.secret
      - .spec.secret.key
      - .spec.secret.value
      - .spec.webhook_secret
      - .spec.webhook_secret.key
      - .spec.webhook_secret.value
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PruneLast=true
